-- ============================================================
-- Angket — Supabase schema
-- Run this in the Supabase Dashboard → SQL Editor on the
-- project referenced by SUPABASE_URL in backend/.env.
-- ============================================================

-- ---------- Profiles (extends auth.users) ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

-- ---------- Categories ----------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  value text not null unique,
  label_en text not null,
  label_km text,
  description_en text,
  description_km text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- ---------- Reports ----------
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  title_en text not null,
  title_km text,
  description_en text not null,
  description_km text,
  category text not null,
  platform text,
  contact_method text,
  amount_lost text,
  date_occurred date,
  screenshot_url text,
  status text not null default 'published'
    check (status in ('pending', 'published', 'approved', 'rejected')),
  reported_count int not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists reports_category_idx on public.reports (category);
create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

-- ---------- Subscriptions ----------
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  plan text not null check (plan in ('free', 'premium')),
  status text not null default 'active'
    check (status in ('active', 'canceled', 'expired', 'pending')),
  started_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists subscriptions_user_idx on public.subscriptions (user_id);

-- ---------- Verifications ----------
create table if not exists public.verifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  type text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

-- ---------- Seed categories ----------
insert into public.categories (value, label_en, label_km, description_en, description_km) values
  ('fake-job', 'Fake Job', 'ការងារក្លែងក្លាយ',
   'Job offers designed to take your money, not give you work.',
   'ការផ្ដល់ការងារដែលរៀបចំដើម្បីយកលុយរបស់អ្នក'),
  ('investment', 'Investment', 'ការវិនិយោគក្លែងក្លាយ',
   'Fake trading schemes and guaranteed-return promises.',
   'ក្រុមវិនិយោគក្លែងក្លាយ និងការសន្យាផ្ដល់ការត្រឡប់មកវិញ'),
  ('prize', 'Prize / Giveaway', 'រង្វាន់ក្លែងក្លាយ',
   'Free prizes that are never free.',
   'រង្វាន់ឥតគិតថ្លៃដែលមិនដែលឥតគិតថ្លៃ'),
  ('phishing', 'Phishing', 'ការបញ្ឆោតយកព័ត៌មាន',
   'Fake emails and messages that steal passwords and data.',
   'អ៊ីមែល និងសារក្លែងក្លាយដែលលួចពាក្យសម្ងាត់ និងទិន្នន័យ'),
  ('fake-seller', 'Fake Seller', 'អ្នកលក់ក្លែងក្លាយ',
   'Online sellers who vanish after payment.',
   'អ្នកលក់តាមអ៊ីនធឺណិតដែលបាត់ខ្លួនបន្ទាប់ពីទទួលប្រាក់'),
  ('impersonation', 'Impersonation', 'ការក្លែងបន្លំអត្តសញ្ញាណ',
   'Scammers pretending to be people you trust.',
   'ក្រុមបោកប្រាស់ក្លែងធ្វើជាអ្នកដែលអ្នកជឿជាក់')
on conflict (value) do nothing;

-- ---------- New user trigger: auto-create profile ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'phone',
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- Seed an admin profile (change email to your admin) ----------
-- The first admin user must be created through the app's signup, then you can
-- promote them to admin with:
--   update public.profiles set role = 'admin' where id = '<user-uuid>';
